### ISSUE TITLE
RFBNet如何转换onnx格式

### ISSUE THREAD

**Issue by runrunrun1994** [xiaoxiaotao/person-detection#3]
您好！
　　　我在将pytorch模型转onnx再转trt模型过程遇到算子不支持的情况的，比如这一句loc.view(loc.size(0), -1, 4)会报　While parsing node number 124 [Gather]解析错误，请问
您针对pytorch中的torch.view操作有使用替代操作吗？

**Comment by runrunrun1994** [comment]
我根据问题１弄好了

**Comment by Ai-ZJ** [comment]
> 我根据问题１弄好了

能否分享一下方法？
